parser: 'babel-eslint'
plugins:
  - react
  - react-hooks
  - prettier
extends:
  - plugin:prettier/recommended
  - prettier/react
settings:
  react:
    version: "16.8.5"
rules:
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  react/jsx-uses-vars: 
    - 1
  react-hooks/rules-of-hooks:
    - "error"